#!/usr/bin/env python3

from secrets import choice
import os, sys

argc = len(sys.argv)

if argc == 0:
    print("argc is 0!")
    sys.exit(1)
elif argc == 2:
    wordlist_filename = sys.argv[1]
    word_count = 1
elif argc == 3:
    wordlist_filename = sys.argv[1]
    try:
        word_count = int(sys.argv[2])
    except ValueError:
        print("Usage: {} wordlist_file [word_count]".format(sys.argv[0]))
        sys.exit(1)
else:
    print("Usage: {} wordlist_file [word_count]".format(sys.argv[0]))
    sys.exit(1)

if not(wordlist_filename == "-" or os.path.isfile(wordlist_filename)):
    print("Wordlist file does not exist or not a file: {}".format(wordlist_filename))
    sys.exit(1)

if wordlist_filename == "-":
    wordlist_file = sys.stdin
else:
    wordlist_file = open(wordlist_filename)

wordlist = {}
for line in wordlist_file:
    (key, word) = line.strip().split()
    wordlist[key] = word

keys = list(wordlist.keys())

rolls = []
words = []
for _ in range(word_count):
    roll = choice(keys)
    rolls.append(roll)
    words.append(wordlist[roll])

print(" ".join(rolls))
print(" ".join(words))
