#!/bin/sh

set -eu

debug() {
	if [ -n "${DEBUG:-}" ]; then
		echo "${0##*/}:" "$@" >&2
	fi
}

usage() {
	echo "Usage: $0 region/cluster-name [role]" >&2
	exit 1
}

if [ "$#" -lt 1 ]; then
	usage
fi

region="${1%/*}"
cluster_name="${1#*/}"

if [ -z "$region" ] || [ -z "$cluster_name" ]; then
	usage
fi

role="${2:-""}"

eks_token="$(cache -g -t "aws-eks-token" -n "${region}_${cluster_name}" || true)"

if [ -z "$eks_token" ]; then
	debug "Loading EKS credentials for: ${region}/${cluster_name}"

	eks_token="$(aws ${region:+--region $region} eks get-token --cluster-name "$cluster_name" ${role:+--role $role})"
	eks_token_expiration="$(TZ=UTC date -j -f "%Y-%m-%dT%H:%M:%SZ" "$(echo "$eks_token" | jq -r '.status.expirationTimestamp')" +%s)"

	printf "%s" "$eks_token" | cache -s -t "aws-eks-token" -n "${region}_${cluster_name}" -e "$eks_token_expiration"
fi

echo "$eks_token"
