#!/bin/sh

# Loads AWS credentials and caches them locally until it's expiration

set -eu

debug() {
	if [ -n "${DEBUG:-}" ]; then
		echo "${0##*/}:" "$@" >&2
	fi
}

get_pass_field() {
	# shellcheck disable=SC2039
	local field passdata
	field="$1"
	passdata="$2"

	printf "%s\n" "$passdata" | awk "/^${field}: / { print \$2 }"
}

if [ $# != "1" ]; then
	echo "${0##*/}:" "Usage: $0 aws_account" >&2
	exit 1
fi

aws_account="$1"

aws_creds="$(cache -g -t aws-session -n "$aws_account" || true)"

if [ -z "$aws_creds" ]; then
	debug "Getting new AWS credentials for account: $aws_account"

	pass_entry="$aws_account"

	passdata="$(pass show "$pass_entry")"

	pass_aws_access_key_id="$(get_pass_field "AWS-Access-Key-Id" "$passdata")"
	pass_aws_secret_access_key="$(get_pass_field "AWS-Secret-Access-Key" "$passdata")"
	pass_mfa_serial="$(get_pass_field "AWS-MFA-Serial" "$passdata")"
	pass_mfa_token="$(PASSWORD_STORE_ENABLE_EXTENSIONS=true pass otp "$pass_entry")"

	# shellcheck disable=SC2140
	read -r aws_session_access_key_id aws_session_secret_access_key aws_session_token aws_session_expiration <<EOI
$(
	AWS_ACCESS_KEY_ID="$pass_aws_access_key_id" \
	AWS_SECRET_ACCESS_KEY="$pass_aws_secret_access_key" \
	AWS_SECURITY_TOKEN="" AWS_SESSION_TOKEN="" \
	AWS_CREDENTIAL_EXPIRATION="" \
	aws sts get-session-token \
		--duration-seconds 900 \
		${pass_mfa_serial:+"--serial-number" "$pass_mfa_serial"} \
		${pass_mfa_token:+"--token-code" "$pass_mfa_token"} \
		--query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken,Expiration]" \
		--output text
)
EOI

	#aws_creds="AWS_ACCESS_KEY_ID="$aws_session_access_key_id"; export AWS_ACCESS_KEY_ID
#AWS_SECRET_ACCESS_KEY="$aws_session_secret_access_key"; export AWS_SECRET_ACCESS_KEY
#AWS_SECURITY_TOKEN="$aws_session_token"; export AWS_SECURITY_TOKEN
#AWS_SESSION_TOKEN="$aws_session_token"; export AWS_SESSION_TOKEN
#AWS_SESSION_EXPIRATION="$aws_session_expiration"; export AWS_SESSION_EXPIRATION"

	aws_creds="{
  \"Version\": 1,
  \"AccessKeyId\": \"$aws_session_access_key_id\",
  \"SecretAccessKey\": \"$aws_session_secret_access_key\",
  \"SessionToken\": \"$aws_session_token\", 
  \"Expiration\": \"$aws_session_expiration\"
}"

	aws_creds_expiration="$(TZ=UTC date -j -f "%Y-%m-%dT%H:%M:%SZ" "$aws_session_expiration" +%s)"

	printf "%s" "$aws_creds" | cache -s -t aws-session -n "$aws_account" -e "$aws_creds_expiration"
fi

echo "$aws_creds"
